{% set version = "0.09" %}

package:
  name: perl-convert-pheno
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MR/MRUEDA/Convert-Pheno-{{version}}.tar.gz
  sha256: 04b00543c68609d65be681886ee4aeab21765759bff9558017e240e7296908ff

build:
  number: 0
  noarch: generic
  
requirements:
  build: 
    - {{ compiler('c') }}
    - make
  host:
    - perl
    - perl-app-cpanminus
    - perl-dbi
    - perl-dbd-sqlite
    - perl-file-sharedir-install
    - perl-json-xs
    - perl-perlio-gzip
    # - perl-sort-naturally
    - perl-test-exception

  run:
    - perl
  
test:
  # Perl 'use' tests
  imports:
    - Convert::Pheno
    # Can't locate Convert/Pheno.pm in @INC

about:
  home: https://github.com/CNAG-Biomedical-Informatics/convert-pheno
  license: Artistic License 2.0
  summary: A software toolkit for the interconversion of standard data models for phenotypic data
  doc_url: https://cnag-biomedical-informatics.github.io/convert-pheno

