package:
  name: perl-convert-pheno
  version: "0.0.1"

source:
  url: https://cpan.metacpan.org/authors/id/M/MR/MRUEDA/Convert-Pheno-0.04.tar.gz
  sha256: bb33388b29b8f371776bf850e84103a36e4cb8bf78cec5f0ecf666b8504f5f19

build:
  number: 0
  noarch: generic
  
requirements:
  build: 
    - {{ compiler('c') }}
    - make
  host:
    - perl
    - perl-app-cpanminus
    - zlib
    - perl-perlio-gzip
    - perl-io-socket-ssl
    - perl-json-xs
    - perl-sort-naturally
    - perl-test-exception
    - perl-dbi
    - perl-dbd-sqlite
    - perl-moo

  run:
    - perl
    - zlib
  
test:
  # Perl 'use' tests
  imports:
    - Convert::Pheno
    # Can't locate Convert/Pheno.pm in @INC

about:
  home: https://github.com/CNAG-Biomedical-Informatics/convert-pheno
  license: Artistic License 2.0
  summary: A software toolkit for the interconversion of standard data models for phenotypic data
  doc_url: https://cnag-biomedical-informatics.github.io/convert-pheno

