package:
  name: convert-pheno
  version: "0.0.1"

source:
  url: https://github.com/CNAG-Biomedical-Informatics/convert-pheno-ui/raw/main/convert-pheno.tar.gz
  sha256: db113eff07ff9d3e4eafbc3628d0729307f0bb1c5ccbad2fb339b72e880083ea

build:
  number: 0
  noarch: generic
  
requirements:
  build: 
    - {{ compiler('c') }}
    - make
  host:
    - perl
    - perl-app-cpanminus

  run:
    - perl
  
test:
  import:
    - Convert::Pheno

about:
  home: https://github.com/CNAG-Biomedical-Informatics/convert-pheno
  license: Artistic License 2.0
  summary: 'A software toolkit for the interconversion of standard data models for phenotypic data'

